---

- name: Update all packages
  apt:
    name: '*'
    update_cache: yes
    state: latest

- name: Upgrade all packages
  apt:
    upgrade: full

- name: Add user "{{ username }}"
  user:
    name: "{{ username }}"
    shell: /bin/bash
    group: sudo
    password: "{{ password }}"
    state: present  
...

