---

- name: Update all packages
  apt:
    name: '*'
    update_cache: yes
    state: latest
  when: update | bool

- name: Upgrade all packages
  apt:
    upgrade: full
  when: update | bool

- name: Install packages
  apt:
    name: 
      - python3
      - python3-pip
      - tmux
      - vim
      - nano
      - bridge-utils
      - net-tools
      - git
      - ansible
      - mlocate
      - bind9
      - dnsutils
    state: latest

... 
