---

- name: Install packages
  apt:
    name: 
      - net-tools
      - git
      - ansible
      - mlocate
    state: latest

- name: Update all packages
  apt:
    name: '*'
    update_cache: yes
    state: latest
  when: update | bool

- name: Upgrade all packages
  apt:
    upgrade: full
  when: update | bool

... 
