---

- name: Install bind packages
  apt:
    name:
      - bind9
      - bind9utils
      - bind9-doc
      - dnsutils

- name: Copy over templates
  template:
    src: "{{ item }}"
    dest: /etc/bind/{{ item | basename | regex_replace('\.j2$', '') }}
  with_fileglob:
    - ../templates/*.j2
  when: machine == "management"
  register: bind

- name: Restart bind9
  service:
    name: bind9
    state: restarted
    enabled: yes
  when: bind.changed | bool and machine == "management"
...
