---

- name: Pull the ceph-ansible repo
  git:
    repo: "https://github.com/ceph/ceph-ansible.git"
    clone: yes
    dest: /home/ubuntu/test/ceph-ansible
    version: stable-5.0
  when: machine == "management"

- name: Copy over hosts file
  template:
    src: hosts
    dest: /home/ubuntu/test/ceph-ansible/hosts
  when: machine == "management"

- name: Copy over site.yml file
  copy:
    src: site.yml
    dest: /home/ubuntu/test/ceph-ansible/site.yml
  when: machine == "management"

- name: Copy over var file
  copy:
    src: all.yml
    dest: /hom/ubuntu/test/ceph-ansible/group_vars/all.yml
  when: machine == "management" 

...
