---

- name: Flush iptables
  iptables:
    flush: yes
  when: machine == "management" and nat | bool

- name: Copy over iptables config
  copy:
    src: iptables-config
    dest: /tmp/
  when: machine == "management"

- name: Setup iptables
  community.general.iptables_state:
    state: restored
    path: /tmp/iptables-config
  when: machine == "management"
  
- name: Delete iptables-config
  file:
    path: /tmp/iptables-config
    state: absent
  when: machine == "management"

- name: Enabling packet forwarding
  copy:
    src: ip_forward
    dest: /proc/sys/net/ipv4/ip_forward
  when: machine  == "management"

- name: Copy over management-cloud-init.example
  copy:
    src: management-cloud-init.example
    dest: /etc/netplan/cloud-init.example
  when: machine == "management"

- name: Copy over controller-cloud-init.example
  copy:
    src: controller-cloud-init.example
    dest: /etc/netplan/cloud-init.example
  when: machine == "controller"

- name: Copy over compute-cloud-init.example
  copy:
    src: compute-cloud-init.example
    dest: /etc/netplan/cloud-init.example
  when: machine == "compute"

- name: Copy over storage-cloud-init.example
  copy:
    src: storage-cloud-init.example
    dest: /etc/netplan/cloud-init.example
  when: machine == "storage"

...
                                     
