---

- name: Deploy an openstack instance
  hosts: all
  remote_user: ubuntu
  become: yes

  vars_files:
    - "vars/false.yml"

  roles:
    - machine_setup
    - update_machine
    - veth_pairs
    - docker

...
