---

- name: Deploy an openstack instance
  hosts: all
  remote_user: ubuntu
  become: yes

  vars_files:
    - "vars/vars.yml"

  roles:
    - setup
    - update
    - nat
    - veth
    - docker
    - ceph
    - dns
    - docker-images
    - pyenv
    - ceph-integration
...
